### ISSUE TITLE
Custom format strings for numbers

### ISSUE THREAD

**Issue by erik-kallen** [Saltarelle/SaltarelleCompiler#135]
Support custom format strings (eg. "0.00") for numbers: http://msdn.microsoft.com/en-us/library/0c899ak8.aspx. Currently only standard format strings (eg. "D2") are supported.

**Comment by geoffreymcgill** [comment]
Looks like this functionality is fully implemented in [Bridge](http://bridge.net/). 

http://deck.net/cb9720eb01924616a2472a2cb72045ce/left
