### ISSUE TITLE
Call for help: New website

### ISSUE THREAD

**Issue by erik-kallen** [Saltarelle/SaltarelleCompiler#230]
I have come to the conclusion that the website (www.saltarelle-compiler.com) is not as good as the project deserves. This is an open thread where everyone can pitch in their ideas of what should be on the new site once it is created:

Some ideas of mine:
- The layout needs to be replace (with what?). Should probably use Bootstrap.
- Improved libary list: Should be able to show version history for libraries. Everyone should be able to add a library to the list (by creating an account on the site).
- Examples and tutorials (the more the better)
- Forum (replace the current one).
- "Try It", a textbox where you write C# and see the generated JS. Bonus points if we can compile NRefactory and run it in the browser to provide auto-completion and syntax highlighting, but I have a feeling that it would be a sh*tload of work.
- Tutorial videos.

Also, if you are willing to help with this, you are very welcome.

**Comment by geoffreymcgill** [comment]
Looks like this issue can be safely closed as [Bridge.NET](http://bridge.net/) and [Deck.NET](http://deck.net/) seem to implement much of what is discussed in this thread.
