### ISSUE TITLE
Xamarin Studio / OS X

### ISSUE THREAD

**Issue by Zambiorix** [Saltarelle/SaltarelleCompiler#298]
Hi,

I would love to start writing Node.js apps using the Saltarelle compiler but I can't find any documentation on how to use the compiler in Xamarin Studio. Is this not supported?

Thanks
Gerd

**Comment by geoffreymcgill** [comment]
[Bridge.NET](http://bridge.net/) supports installation and compilation on Xamarin Studio, Mono Develop, Visual Studio Code (Win, Mac, Linux) and of course Visual Studio.

http://bridge.net/download

Hope this helps.
