### ISSUE TITLE
Use extern in [Import]ed libraries

### ISSUE THREAD

**Issue by nippur72** [Saltarelle/SaltarelleCompiler#326]
It's not a bug, just a suggestion: the whole runtime library (and user-written libraries as well) is written by providing an empty body to imported methods or properties. But this is not necessary as there is the `extern` keyword that lets you not specify the body. For example:

``` C#
[InlineCode("{$System.Script}.contains({this}, {item})")]
public bool Contains(T item) {
   return false;
}
```

can be simplified into

``` C#
[InlineCode("{$System.Script}.contains({this}, {item})")]
public extern bool Contains(T item);
```

Perhaps this fact can be mentioned in the website documentation.

**Comment by geoffreymcgill** [comment]
Now supported in [Bridge](http://bridge.net/).
