### ISSUE TITLE
The [Imported] attribute could be confusing

### ISSUE THREAD

**Issue by JechoJekov** [Saltarelle/SaltarelleCompiler#371]
One might expect that applying the `[Imported]` attribute would imply intrinsic properties rather than `get_` and `set_` methods. As it seems this is not the case.

Perhaps this could be clarified in the documentation.

**Comment by geoffreymcgill** [comment]
In [Bridge](http://bridge.net/), applying the `[External]` and `[ObjectLiteral]` attributes to the class will generate the expected intrinsic property call in js.

http://deck.net/60536eb937eb6c070520701fcf8d5c6b

```cs
public class Program
{
    public static void Main()
    {
        var p = new Person
        {
            Name = "Frank"
        };
        
        Console.WriteLine(p.Name);
    }
}

[External]
[ObjectLiteral]
public class Person
{
    public string Name { get; set; }
}
```

Hope this helps.
