### ISSUE TITLE
Saltarelle can do this...

### ISSUE THREAD

**Issue by JHemingway** [Saltarelle/SaltarelleCompiler#373]
Hey guys,
I am not sure if this is the best place for this, but I couldn't find a Saltarelle community forum that was active.

If you are interested in a practical example of what you can do with Saltarelle then check out this game that is completely written using Saltarelle.

Here is a write up on how it was written in Saltarelle: http://hemingwaygames.com/blog/postbug-compiling-csharp-to-javascript

This is a video of the game in action: https://www.youtube.com/watch?v=tbQueeJT71w

And you can play it here: http://postbug.hemingwaygames.com/

Lastly here is a bit of a chat on the pros / cons on cross compiling around this project: http://www.reddit.com/r/csharp/comments/2potcw/postbug_technical_overview_compiling_c_to/

Again, I am sorry if this is the incorrect forum to post this information, but I am not sure how else to communicate with the Saltarelle community...

**Comment by geoffreymcgill** [comment]
Very cool @HemingwayGames.

Be sure to contact us if you would like any assistance if upgrading to [Bridge](http://bridge.net/). We would be happy to assist.
