### ISSUE TITLE
Null compare issue

### ISSUE THREAD

**Issue by n9** [Saltarelle/SaltarelleCompiler#377]
Let's have the following C# code:

```
public class Foo
{
    public static implicit operator string(Foo foo)
    {
        return null;
    }
}

public class Test
{
    public static bool TestFoo(Foo foo)
    {
        return foo == null;
    }
}
```

The method `Test.TestFoo` is compiled into:

```
$Test.testFoo = function(foo) {
    return ss.isNullOrUndefined($Foo.op_Implicit(foo));
};
```

I think, it should should not invoke the implicit operator `$Foo.op_Implicit()`.

**Comment by n9** [comment]
The bad thing on this issue is, that it causes infinite recursion in situations like:

    public class Foo
    {
        public string Bar;

        public static implicit operator string(Foo foo)
        {
            return foo == null ? null : foo.Bar;
        }
    }

Since, the compiled JavaScript for the implicit operator calls itself:

	$Foo.op_Implicit = function(foo) {
		return (ss.isNullOrUndefined($Foo.op_Implicit(foo)) ? null : foo.bar);
	};

**Comment by erik-kallen** [comment]
Yes, this seems to be a bug (probably in NRefactory)

**Comment by geoffreymcgill** [comment]
It appears the original sample provided in this thread is working correctly with [Bridge](http://bridge.net/).

http://deck.net/8f03688bf601bf2bad3e5a94a33dcd46

```cs
public class Program
{
    public static void Main()
    {
        var foo = new Foo();
        foo.Bar = "Success";
        
        var result = Test.TestFoo(foo);
        
        // Should be false
        Console.WriteLine(result);
        
        // Should be "Success"
        Console.WriteLine((string)foo);
    }
}

public class Foo
{
    public string Bar;
    
    public static implicit operator string(Foo foo)
    {
        return foo == null ? null : foo.Bar;
    }
}

public class Test
{
    public static bool TestFoo(Foo foo)
    {
        return foo == null;
    }
}
```
