### ISSUE TITLE
InlineCode redundancies

### ISSUE THREAD

**Issue by TriEdgeAIDeprecated** [Saltarelle/SaltarelleCompiler#380]
Not sure if this is an issue, but here goes:

Example C# Code:

```
[InlineCode("{a} * {a} + {b}")]
void DoStuff(int a, int b) { ... }

DoStuff(x + x, y);
```

Will get translated to:

```
(x + x) * (x + x) + y;
```

While this seems a better translation:

```
var _arg0 = x + x;
_arg0 * arg0 + y;
```

Maybe you could introduce an optional boolean in InlineCode which would determine whether such redundancies should be dealt with or not?

**Comment by TriEdgeAI** [comment]
Oh, wait. It sort of does that. Here is my actual C# code:

	[InlineCode("{a}.x + {b}.y * {a}.z + {b}.x")]
	static float DoSomething(Vector3 a, Vector3 b)
	{
		throw new NotSupportedException(); 
	}

	static void Main()
	{
		Vector3 a = new Vector3(1.0f, 2.0f, 3.0f);
		Vector3 b = new Vector3(11.0f, 12.0f, 13.0f);
		Vector3 c = new Vector3(21.0f, 22.0f, 23.0f);

		Debug.Log(DoSomething(a + b, b * c));
	}

And the resulting JavaScript:

	var a = new UnityEngine.Vector3.$ctor1(1, 2, 3);
	var b = new UnityEngine.Vector3.$ctor1(11, 12, 13);
	var c = new UnityEngine.Vector3.$ctor1(21, 22, 23);
	var $t1 = UnityEngine.Vector3.op_Addition(a, b);
	var $t2 = UnityEngine.Vector3.op_Multiply$2(b, c);
	console.info(ss.clone(UnityEngine.Vector3, $t1).x + ss.clone(UnityEngine.Vector3, $t2).y * ss.clone(UnityEngine.Vector3, $t1).z + ss.clone(UnityEngine.Vector3, $t2).x);

It still appears to have some issues, though.

**Comment by erik-kallen** [comment]
Can you please provide more information about which issues it has?

**Comment by TriEdgeAI** [comment]
It's performing clone on $t1 and $t2 two times each, while a single clone would be sufficient. In fact the clones are pointless in this certain situation anyways.

**Comment by erik-kallen** [comment]
Yes, you are right

**Comment by geoffreymcgill** [comment]
It appears the original sample provided in this issue is returning the correct expected result in [Bridge](http://bridge.net/).

In Bridge, the equivalent of the `[InlineCode]` attribute is `[Template]`.

http://deck.net/8ae578935c9117661066bb6f47eee9b5

```cs
public class Program
{
    public static void Main()
    {
        var a = DoStuff(2 + 2, 5);
        
        // should be 21
        Console.WriteLine(a);
    }
    
    [Template("{a} * {a} + {b}")]
    static int DoStuff(int a, int b) 
    {
        return a * b;
    }
}
```
