### ISSUE TITLE
enum .ToString() returns a number and not the actual value name

### ISSUE THREAD

**Issue by TriEdgeAIDeprecated** [Saltarelle/SaltarelleCompiler#384]
Example:

```
enum Test
{
    Alfa = 1,
    Beta = 2
}

Test test = Test.Alfa;
Console.WriteLine(test.ToString()); // this will print 1, but it should print Alfa
```

**Comment by erik-kallen** [comment]
Do you have an idea of how to implement this?

**Comment by TriEdgeAI** [comment]
Look-up table? { "1": "Alfa", "2": "Beta" }

**Comment by erik-kallen** [comment]
The problem is that an enum does not have its own type, it is represented by a regular int (or string in case of [NamedValues] enums). So the method ending up being called is ```Number.toString```.

**Comment by geoffreymcgill** [comment]
Just to close this issue off for others that might run into this problem, this functionality is supported correctly in [Bridge](http://bridge.net/).

http://deck.net/29c2bc44011dc1942b3d697eeccf342b

```cs
public class Program
{
    public static void Main()
    {
        Test test = Test.Alfa;
        Console.WriteLine(test.ToString());
    }
}

enum Test
{
    Alfa = 1,
    Beta = 2
}
```

Hope this helps.
