### ISSUE TITLE
Implement all C# 6 features

### ISSUE THREAD

**Issue by erik-kallen** [Saltarelle/SaltarelleCompiler#403]
This will be done after C# 6 is officially released, because I do not want to do unnecessary work to support features that are cut before C# 6 is released (which has happened to inline variable declarations, primary constructors and, a few days ago, parameterless struct constructors).

**Comment by erik-kallen** [comment]
Implemented in Bridge 2.0

**Comment by txdv** [comment]
o god, stop teasing, start releasing!

**Comment by txdv** [comment]
Also, any news on the release date of the test build?

**Comment by geoffreymcgill** [comment]
> Also, any news on the release date of the test build?

News on Bridge 2.0 is being mostly tracked in Issue #430.
