### ISSUE TITLE
[2.6.2] Array of structures is not initialized on creation

### ISSUE THREAD

**Issue by JechoJekov** [Saltarelle/SaltarelleCompiler#420]
Saltarelle compiler does not initialize array of structures when the array is created which is unexpected and different from the behavior of the .NET Framework.

The following code:

```
var p = new int[3];
((dynamic)System.Html.Window.Instance).console.log(p[0]);
```

displays "undefined".

This behavior has obvious performance consequences. However, IMO it should be document at some obvious place since it is unexpected.

Workaround: Use "Array.Repeat" to create an array.

**Comment by erik-kallen** [comment]
Yes, I will look at this in v3.

**Comment by geoffreymcgill** [comment]
Looks like this sample is returning the correct result in [Bridge](http://bridge.net/).

http://deck.net/ec79cb23323df25d369729dc5eecf471

```cs
public class Program
{
    public static void Main()
    {
        var p = new int[3];
        
        Console.WriteLine(p[0]);
    }
}
```

Hope this helps.
