### ISSUE TITLE
Boolean XORs generate incorrect result

### ISSUE THREAD

**Issue by sdarnell** [Saltarelle/SaltarelleCompiler#431]
Take two boolean values a and b, and XOR them together in C# and you get a boolean result.
However, C# `a ^ b` generates Javascript `a ^ b`. Which is pretty close, but ...

The Javascript version generates either a 0 or a 1, which is fine in most cases, but fails when the calling code does an explicit === comparison with `true` or `false`.

There's probably a few options to make it do the right thing, such as wrap in a `!!` e.g. `!!(a ^ b)`.

**Comment by erik-kallen** [comment]
You are right, didn't think of taht
