### ISSUE TITLE
int.Parse() gets translated to parseInt(), which isn't precise

### ISSUE THREAD

**Issue by TriEdgeAI** [Saltarelle/SaltarelleCompiler#433]
For example if you pass an empty string "" to int.Parse() an exception would be thrown. That's not the case with parseInt(), it will always return NaN instead.

**Comment by craigkovatch** [comment]
I've noticed this too...but I actually prefer this, C#'s is too much of a pain to use. If this is "fixed", please leave an option somewhere for using JS "bare" parseInt().

**Comment by vladimir-angelov-1337** [comment]
True, but when porting existing C# code, someone might've written a try-catch around that, and it wouldn't work as expected :)

**Comment by craigkovatch** [comment]
I agree it should be fixed! Just would like an option to switch back to the JS bare function when that happens.

**Comment by geoffreymcgill** [comment]
Looks like the correct functionality of both `int.Parse("")` and `parseInt()` is included in [Bridge](http://bridge.net/). 

I ran the following samples and they appear to return the correct expected result.

http://deck.net/7a3bfdfc78ef349fedbc0f9b27346cac

```cs
public class Program
{
    public static void Main()
    {
        try
        {
	        var tmp = int.Parse("");
        }
        catch(FormatException ex)
        {
	        Console.WriteLine(ex.Message);
        }
        
        var val = Script.ParseInt("");
        
        Console.WriteLine(val);
    }
}
```

Hope this helps.
