### ISSUE TITLE
Add support for InternalsVisibleTo attribute

### ISSUE THREAD

**Issue by thecoderok** [Saltarelle/SaltarelleCompiler#436]
Currently Saltarelle does not support InternalsVisibleTo attribute. It makes unit testing harder since it won't compile when I call method that is visible in JS but not in C#. 
Currently I have to cast object/type to dynamic, but this hack fails when we minify javascript.
Is there any particular reason why InternalsVisibleTo not supported? Can someone please add it? Or if you give some hints I could try to do it.

Thank you!

**Comment by erik-kallen** [comment]
No, no reason, it is just missing. Perhaps it will need to be implemented just in Bridge 2 depending on whether NRefactory supports the attribute

**Comment by geoffreymcgill** [comment]
Bridge does not currently (v15.6.0) support this functionality, but we've logged the feature request and hope to include in the release (v15.7.0). 

https://github.com/bridgedotnet/Bridge/issues/2190

**Comment by geoffreymcgill** [comment]
A pull request has been submitted to Bridge with **InternalsVisibleTo** attribute support. The pr will be reviewed, and we expect to include in the Bridge 15.7.0 release (mid-Jan 2017).

Hope this helps.
