### ISSUE TITLE
If the data exict

### ISSUE THREAD

**Issue by BolatovAlau** [Saltarelle/SaltarelleCompiler#440]
Hi All I've got a really bad problem. I want to know whether the record exists in the database using Saltarelle. Method or something else which tells me that 
Thanks

**Comment by geoffreymcgill** [comment]
Saltarelle generates JavaScript which will run in the browser. This code cannot connect directly to your database. 

I would recommend creating a Web API layer that will return a JSON response to be consumed on the client in JavaScript. This Web API layer would be running on your server and could communicate with your Database. 

Hope this helps.
